name: riverpod_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  adaptive_dialog:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  gap:
  hooks_riverpod:
  recase:
  simple_logger:
  state_notifier:
  uuid:

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono:

flutter:
  uses-material-design: true
