name: riverpod_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  adaptive_dialog:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_hooks: '>=0.16.0'
  gap: '>=2.0.0-0'
  hooks_riverpod: '>=0.14.0'
  recase: '>=4.0.0-0'
  simple_logger:
  state_notifier:
  uuid: '>=3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

flutter:
  uses-material-design: true
